before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/ddns-updater/main.go
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    targets:
      # See https://goreleaser.com/customization/build/
      - linux_amd64
      - linux_386
      - linux_arm64
      - linux_arm_7
      - linux_arm_6
      - linux_arm_5
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_386
      - windows_arm64
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
