apiVersion: v1
kind: Secret
metadata:
  name: ddns-updater-config
type: Opaque
stringData:
  CONFIG: '{"settings":[{"provider":"ddnss","provider_ip":true,"domain":"YOUR-DOMAIN","owner":"@","username":"YOUR-USERNAME","password":"YOUR-PASSWORD","ip_version":"ipv4"}]}'
